targets:
  $default:
    sources:
        - lib/**
        - graphql/**
    builders:
      artemis:
        options:
            fragments_glob: graphql/fragments/**.graphql
            schema_mapping:
                - output: lib/graphql/api.graphql.dart
                  schema: graphql/schema.gql
                  queries_glob: graphql/{mutations,queries,subscriptions}/**.graphql
                  naming_scheme: pathedWithFields
            scalar_mapping:
                - graphql_type: DateTime
                  dart_type: DateTime
