targets:
  $default:
    sources:
        - lib/**
        - graphql/**
    builders:
      artemis:
        options:
            fragments_glob: graphql/fragments/**.graphql
            schema_mapping:
                - output: lib/graphql/api.graphql.dart
                  schema: graphql/schema.gql
                  queries_glob: graphql/queries/**.graphql
                  naming_scheme: pathedWithFields
                - output: lib/graphql/mutations.graphql.dart
                  schema: graphql/schema.gql
                  queries_glob: graphql/mutations/*.graphql
                  naming_scheme: pathedWithFields
