name: Taag
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.0
  graphql_flutter: ^3.0.0
  provider: ^4.3.1
  json_serializable: ^3.0.0
  meta: '>=1.0.0 <2.0.0' # only if you have non nullable fields
  gql: '>=0.7.3 <1.0.0'
  flutter_staggered_grid_view: "^0.3.1"
  flutter_login: 
    git:
      url: git@github.com:winsonhys/flutter_login.git
  google_fonts: ^1.1.0
  lottie: ^0.5.1
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0+1
  auto_size_text: ^2.1.0
  firebase_core: "0.5.0-dev.2"
  firebase_auth: "0.17.0-dev.1"
  get: ^3.4.3
  sliding_up_panel: ^1.0.2
  carousel_slider: ^2.2.1
  badges: ^1.1.1
  flushbar: ^1.10.4
  flutter_icons: ^1.1.0
  flutter_hooks: ^0.13.2
  stripe_payment: ^1.0.7
  dartx: ^0.5.0
  supercharged: ^1.10.0
  credit_card_input_form:
    git:
      url: git@github.com:Randevoo/Flutter-Credit-Card-Input-Form.git
  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  
dependency_overrides:
  analyzer: '0.39.14'

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: '6.0.10-beta.1'
  build_runner: ^1.5.0
  pedantic: ^1.9.0
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
