type Query {
  shopItems(where: ShopItemWhereInput, orderBy: [ShopItemOrderByInput!], cursor: ShopItemWhereUniqueInput, take: Int, skip: Int, distinct: [ShopItemDistinctFieldEnum!]): [ShopItem!]!
  shopItem(where: ShopItemWhereUniqueInput!): ShopItem
  user(where: UserWhereUniqueInput!): User
  findMultiCartsByUserId(findMultiCartByUserIdInput: FindMultiOrderByUserIdInput!): MultiOrder!
  findOrdersFromOwnerId(ownerId: String!): [Order!]!
  getPaymentInfo(getPaymentInfoInput: GetPaymentInfoInput!): [PaymentMethod!]!
  getAddresses: [Address!]!
  findUserById(id: String!): User!
}

input ShopItemWhereInput {
  AND: [ShopItemWhereInput!]
  OR: [ShopItemWhereInput!]
  NOT: [ShopItemWhereInput!]
  id: StringFilter
  createdAt: DateTimeFilter
  name: StringFilter
  description: StringFilter
  price: FloatFilter
  imageUrl: StringFilter
  shop: ShopWhereInput
  shopId: StringFilter
  cartItemCounts: CartItemCountListRelationFilter
  refunds: RefundListRelationFilter
}

input StringFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringFilter
}

input NestedStringFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringFilter
}

input DateTimeFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeFilter
}

"""
The javascript `Date` as string. Type represents date and time as the ISO Date string.
"""
scalar DateTime

input NestedDateTimeFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeFilter
}

input FloatFilter {
  equals: Float
  in: [Float!]
  notIn: [Float!]
  lt: Float
  lte: Float
  gt: Float
  gte: Float
  not: NestedFloatFilter
}

input NestedFloatFilter {
  equals: Float
  in: [Float!]
  notIn: [Float!]
  lt: Float
  lte: Float
  gt: Float
  gte: Float
  not: NestedFloatFilter
}

input ShopWhereInput {
  AND: [ShopWhereInput!]
  OR: [ShopWhereInput!]
  NOT: [ShopWhereInput!]
  id: StringFilter
  email: StringFilter
  username: StringFilter
  password: StringFilter
  shopItems: ShopItemListRelationFilter
}

input ShopItemListRelationFilter {
  every: ShopItemWhereInput
  some: ShopItemWhereInput
  none: ShopItemWhereInput
}

input CartItemCountListRelationFilter {
  every: CartItemCountWhereInput
  some: CartItemCountWhereInput
  none: CartItemCountWhereInput
}

input CartItemCountWhereInput {
  AND: [CartItemCountWhereInput!]
  OR: [CartItemCountWhereInput!]
  NOT: [CartItemCountWhereInput!]
  id: StringFilter
  orderId: StringFilter
  order: OrderWhereInput
  itemId: StringFilter
  shopItem: ShopItemWhereInput
  price: FloatFilter
  count: IntFilter
  deletedAt: DateTimeNullableFilter
}

input OrderWhereInput {
  AND: [OrderWhereInput!]
  OR: [OrderWhereInput!]
  NOT: [OrderWhereInput!]
  id: StringFilter
  ownerId: StringFilter
  owner: UserWhereInput
  paymentIntentId: StringNullableFilter
  price: FloatFilter
  cartItemCount: CartItemCountWhereInput
  MultiOrder: MultiOrderWhereInput
  multiOrderId: StringNullableFilter
  PaymentOrder: PaymentOrderWhereInput
  deletedAt: DateTimeNullableFilter
}

input UserWhereInput {
  AND: [UserWhereInput!]
  OR: [UserWhereInput!]
  NOT: [UserWhereInput!]
  id: StringFilter
  email: StringFilter
  username: StringFilter
  password: StringFilter
  dob: DateTimeFilter
  orders: OrderListRelationFilter
  stripe_cust_id: StringFilter
  addresses: AddressListRelationFilter
}

input OrderListRelationFilter {
  every: OrderWhereInput
  some: OrderWhereInput
  none: OrderWhereInput
}

input AddressListRelationFilter {
  every: AddressWhereInput
  some: AddressWhereInput
  none: AddressWhereInput
}

input AddressWhereInput {
  AND: [AddressWhereInput!]
  OR: [AddressWhereInput!]
  NOT: [AddressWhereInput!]
  id: StringFilter
  city: StringFilter
  line1: StringFilter
  line2: StringFilter
  postal: StringFilter
  state: StringFilter
  userId: StringFilter
  user: UserWhereInput
}

input StringNullableFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringNullableFilter
}

input NestedStringNullableFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringNullableFilter
}

input MultiOrderWhereInput {
  AND: [MultiOrderWhereInput!]
  OR: [MultiOrderWhereInput!]
  NOT: [MultiOrderWhereInput!]
  id: StringFilter
  orders: OrderListRelationFilter
  paymentIntentId: StringNullableFilter
  PaymentMultiOrder: PaymentMultiOrderWhereInput
}

input PaymentMultiOrderWhereInput {
  AND: [PaymentMultiOrderWhereInput!]
  OR: [PaymentMultiOrderWhereInput!]
  NOT: [PaymentMultiOrderWhereInput!]
  id: StringFilter
  paymentStatus: EnumPaymentStatusFilter
  multiOrderId: StringFilter
  multiOrder: MultiOrderWhereInput
  paymentIntentId: StringFilter
}

input EnumPaymentStatusFilter {
  equals: PaymentStatus
  in: [PaymentStatus!]
  notIn: [PaymentStatus!]
  not: NestedEnumPaymentStatusFilter
}

enum PaymentStatus {
  UNPAID
  AWAITING_CATURE
  PAID
  REFUNDED
}

input NestedEnumPaymentStatusFilter {
  equals: PaymentStatus
  in: [PaymentStatus!]
  notIn: [PaymentStatus!]
  not: NestedEnumPaymentStatusFilter
}

input PaymentOrderWhereInput {
  AND: [PaymentOrderWhereInput!]
  OR: [PaymentOrderWhereInput!]
  NOT: [PaymentOrderWhereInput!]
  id: StringFilter
  paymentStatus: EnumPaymentStatusFilter
  orderId: StringFilter
  order: OrderWhereInput
  paymentIntentId: StringFilter
}

input DateTimeNullableFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeNullableFilter
}

input NestedDateTimeNullableFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeNullableFilter
}

input IntFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntFilter
}

input NestedIntFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntFilter
}

input RefundListRelationFilter {
  every: RefundWhereInput
  some: RefundWhereInput
  none: RefundWhereInput
}

input RefundWhereInput {
  AND: [RefundWhereInput!]
  OR: [RefundWhereInput!]
  NOT: [RefundWhereInput!]
  id: StringFilter
  shopItem: ShopItemWhereInput
  shopItemId: StringFilter
  description: StringFilter
  paymentIntentId: StringFilter
  stripeRefundId: StringFilter
}

input ShopItemOrderByInput {
  id: SortOrder
  createdAt: SortOrder
  name: SortOrder
  description: SortOrder
  price: SortOrder
  imageUrl: SortOrder
  shopId: SortOrder
}

enum SortOrder {
  asc
  desc
}

input ShopItemWhereUniqueInput {
  id: String
}

enum ShopItemDistinctFieldEnum {
  id
  createdAt
  name
  description
  price
  imageUrl
  shopId
}

type ShopItem {
  id: String!
  createdAt: DateTime!
  name: String!
  description: String!
  price: Float!
  imageUrl: String!
  shopId: String!
  shop: Shop!
  cartItemCounts(where: CartItemCountWhereInput, orderBy: [CartItemCountOrderByInput!], cursor: CartItemCountWhereUniqueInput, take: Int, skip: Int, distinct: [CartItemCountDistinctFieldEnum!]): [CartItemCount!]
  refunds(where: RefundWhereInput, orderBy: [RefundOrderByInput!], cursor: RefundWhereUniqueInput, take: Int, skip: Int, distinct: [RefundDistinctFieldEnum!]): [Refund!]
}

type Shop {
  id: String!
  email: String!
  username: String!
  password: String!
}

input CartItemCountOrderByInput {
  id: SortOrder
  orderId: SortOrder
  itemId: SortOrder
  price: SortOrder
  count: SortOrder
  deletedAt: SortOrder
}

input CartItemCountWhereUniqueInput {
  id: String
}

enum CartItemCountDistinctFieldEnum {
  id
  orderId
  itemId
  price
  count
  deletedAt
}

type CartItemCount {
  id: String!
  orderId: String!
  itemId: String!
  price: Float!
  count: Int!
  deletedAt: DateTime
  shopItem: ShopItem!
}

input RefundOrderByInput {
  id: SortOrder
  shopItemId: SortOrder
  description: SortOrder
  paymentIntentId: SortOrder
  stripeRefundId: SortOrder
}

input RefundWhereUniqueInput {
  id: String
}

enum RefundDistinctFieldEnum {
  id
  shopItemId
  description
  paymentIntentId
  stripeRefundId
}

type Refund {
  id: String!
  shopItemId: String!
  description: String!
  paymentIntentId: String!
  stripeRefundId: String!
}

input UserWhereUniqueInput {
  id: String
  email: String
  username: String
}

type User {
  id: String!
  email: String!
  username: String!
  password: String!
  dob: DateTime!
  stripe_cust_id: String!
  orders(where: OrderWhereInput, orderBy: [OrderOrderByInput!], cursor: OrderWhereUniqueInput, take: Int, skip: Int, distinct: [OrderDistinctFieldEnum!]): [Order!]
  addresses(where: AddressWhereInput, orderBy: [AddressOrderByInput!], cursor: AddressWhereUniqueInput, take: Int, skip: Int, distinct: [AddressDistinctFieldEnum!]): [Address!]
}

input OrderOrderByInput {
  id: SortOrder
  ownerId: SortOrder
  paymentIntentId: SortOrder
  price: SortOrder
  multiOrderId: SortOrder
  deletedAt: SortOrder
}

input OrderWhereUniqueInput {
  id: String
}

enum OrderDistinctFieldEnum {
  id
  ownerId
  paymentIntentId
  price
  multiOrderId
  deletedAt
}

type Order {
  id: String!
  ownerId: String!
  paymentIntentId: String
  price: Float!
  multiOrderId: String
  deletedAt: DateTime
  owner: User!
  cartItemCount: CartItemCount!
  MultiOrder: MultiOrder
  PaymentOrder: PaymentOrder
}

type MultiOrder {
  id: String!
  paymentIntentId: String
  orders(where: OrderWhereInput, orderBy: [OrderOrderByInput!], cursor: OrderWhereUniqueInput, take: Int, skip: Int, distinct: [OrderDistinctFieldEnum!]): [Order!]
  PaymentMultiOrder: PaymentMultiOrder
}

type PaymentMultiOrder {
  id: String!
  paymentStatus: PaymentStatus!
  multiOrderId: String!
  paymentIntentId: String!
}

type PaymentOrder {
  id: String!
  paymentStatus: PaymentStatus!
  orderId: String!
  paymentIntentId: String!
}

input AddressOrderByInput {
  id: SortOrder
  city: SortOrder
  line1: SortOrder
  line2: SortOrder
  postal: SortOrder
  state: SortOrder
  userId: SortOrder
}

input AddressWhereUniqueInput {
  id: String
}

enum AddressDistinctFieldEnum {
  id
  city
  line1
  line2
  postal
  state
  userId
}

type Address {
  id: String!
  city: String!
  line1: String!
  line2: String!
  postal: String!
  state: String!
  userId: String!
}

input FindMultiOrderByUserIdInput {
  user_id: String!
}

input GetPaymentInfoInput {
  stripe_cust_id: String!
}

type PaymentMethod {
  id: String!
  billing_details: StripeCardBillingDetails!
  card: StripeCard!
  created: Float!
  customer: String!
  livemode: Boolean!
}

type StripeCardBillingDetails {
  address: StripeCardBillingAddress!
  email: String!
  name: String!
  phone: String!
}

type StripeCardBillingAddress {
  city: String!
  country: String!
  line1: String!
  line2: String!
  postal_code: String!
  state: String!
}

type StripeCard {
  brand: String!
  country: String!
  description: String!
  exp_month: Float!
  exp_year: Float!
  fingerprint: String!
  funding: String!
  iin: String!
  issuer: String!
  last4: String!
  networks: StripeCardNetworks!
  three_d_secure_usage: StripeCardThreeDSecureUsage!
}

type StripeCardNetworks {
  available: [String!]!
  preferred: String!
}

type StripeCardThreeDSecureUsage {
  supported: Boolean!
}

type Mutation {
  createShop(data: ShopCreateInput!): Shop!
  createShopItem(data: ShopItemCreateInput!): ShopItem!
  removeFromOrder(removeFromOrderInput: RemoveFromOrderInput!): Order
  addToOrder(addToOrderInput: AddToOrderInput!): [Order!]!
  addPaymentInfo(addPaymentInfoInput: AddPaymentInfoInput!): PaymentMethod!
  deletePaymentInfo(deletePaymentInfoInput: DeletePaymentInfoInput!): PaymentMethod!
  payCurrentOrder(payCurrentOrderInput: PayCurrentOrderInput!): Order!
  addAddress(addAddressInput: AddAddressInput!): [Address!]!
  signUp(signUpInput: SignUpInput!): User!
}

input ShopCreateInput {
  id: String
  email: String!
  username: String!
  password: String!
  shopItems: ShopItemCreateManyWithoutShopInput
}

input ShopItemCreateManyWithoutShopInput {
  create: [ShopItemCreateWithoutShopInput!]
  connect: [ShopItemWhereUniqueInput!]
}

input ShopItemCreateWithoutShopInput {
  id: String
  createdAt: DateTime
  name: String!
  description: String!
  price: Float!
  imageUrl: String!
  cartItemCounts: CartItemCountCreateManyWithoutShopItemInput
  refunds: RefundCreateManyWithoutShopItemInput
}

input CartItemCountCreateManyWithoutShopItemInput {
  create: [CartItemCountCreateWithoutShopItemInput!]
  connect: [CartItemCountWhereUniqueInput!]
}

input CartItemCountCreateWithoutShopItemInput {
  id: String
  price: Float!
  count: Int!
  deletedAt: DateTime
  order: OrderCreateOneWithoutCartItemCountInput!
}

input OrderCreateOneWithoutCartItemCountInput {
  create: OrderCreateWithoutCartItemCountInput
  connect: OrderWhereUniqueInput
}

input OrderCreateWithoutCartItemCountInput {
  id: String
  paymentIntentId: String
  price: Float
  deletedAt: DateTime
  owner: UserCreateOneWithoutOrdersInput!
  MultiOrder: MultiOrderCreateOneWithoutOrdersInput
  PaymentOrder: PaymentOrderCreateOneWithoutOrderInput
}

input UserCreateOneWithoutOrdersInput {
  create: UserCreateWithoutOrdersInput
  connect: UserWhereUniqueInput
}

input UserCreateWithoutOrdersInput {
  id: String
  email: String!
  username: String!
  password: String!
  dob: DateTime!
  stripe_cust_id: String
  addresses: AddressCreateManyWithoutUserInput
}

input AddressCreateManyWithoutUserInput {
  create: [AddressCreateWithoutUserInput!]
  connect: [AddressWhereUniqueInput!]
}

input AddressCreateWithoutUserInput {
  id: String
  city: String!
  line1: String!
  line2: String!
  postal: String!
  state: String!
}

input MultiOrderCreateOneWithoutOrdersInput {
  create: MultiOrderCreateWithoutOrdersInput
  connect: MultiOrderWhereUniqueInput
}

input MultiOrderCreateWithoutOrdersInput {
  id: String
  paymentIntentId: String
  PaymentMultiOrder: PaymentMultiOrderCreateOneWithoutMultiOrderInput
}

input PaymentMultiOrderCreateOneWithoutMultiOrderInput {
  create: PaymentMultiOrderCreateWithoutMultiOrderInput
  connect: PaymentMultiOrderWhereUniqueInput
}

input PaymentMultiOrderCreateWithoutMultiOrderInput {
  id: String
  paymentStatus: PaymentStatus
  paymentIntentId: String!
}

input PaymentMultiOrderWhereUniqueInput {
  id: String
}

input MultiOrderWhereUniqueInput {
  id: String
}

input PaymentOrderCreateOneWithoutOrderInput {
  create: PaymentOrderCreateWithoutOrderInput
  connect: PaymentOrderWhereUniqueInput
}

input PaymentOrderCreateWithoutOrderInput {
  id: String
  paymentStatus: PaymentStatus
  paymentIntentId: String!
}

input PaymentOrderWhereUniqueInput {
  id: String
}

input RefundCreateManyWithoutShopItemInput {
  create: [RefundCreateWithoutShopItemInput!]
  connect: [RefundWhereUniqueInput!]
}

input RefundCreateWithoutShopItemInput {
  id: String
  description: String!
  paymentIntentId: String!
  stripeRefundId: String!
}

input ShopItemCreateInput {
  id: String
  createdAt: DateTime
  name: String!
  description: String!
  price: Float!
  imageUrl: String!
  shop: ShopCreateOneWithoutShopItemsInput!
  cartItemCounts: CartItemCountCreateManyWithoutShopItemInput
  refunds: RefundCreateManyWithoutShopItemInput
}

input ShopCreateOneWithoutShopItemsInput {
  create: ShopCreateWithoutShopItemsInput
  connect: ShopWhereUniqueInput
}

input ShopCreateWithoutShopItemsInput {
  id: String
  email: String!
  username: String!
  password: String!
}

input ShopWhereUniqueInput {
  id: String
  email: String
  username: String
}

input RemoveFromOrderInput {
  item_id: String!
  buyer_id: String!
}

input AddToOrderInput {
  item_id: String!
  buyer_id: String!
}

input AddPaymentInfoInput {
  stripe_cust_id: String!
  token: String!
  default: Boolean
}

input DeletePaymentInfoInput {
  paymentMethodId: String!
}

input PayCurrentOrderInput {
  user_id: String!
  order_id: String!
  payment_method_id: String!
}

input AddAddressInput {
  city: String!
  state: String!
  line1: String!
  line2: String!
  postal: String!
}

input SignUpInput {
  email: String!
  password: String!
  displayName: String!
  firstName: String!
  lastName: String!
  dob: DateTime!
}
